// candidate-data.js
// Danh sách 10 ứng viên cố định (không random)
// Dữ liệu đầy đủ, hợp lệ, sẵn sàng import

export const userData = [
  {
    CandidateID: 594737, // 1 Id
    CandidateName: "Bùi Mỹ Uyên", // 2 Họ tên
    Mobile: "0331256963", // 3 Số điện thoại
    Email: "uyenbt.work@gmail.com", // 4 Email
    RecruitmentCampaignNames: null, // 4 Chiến dịch tuyển dụng
    RecruitmentName: "Nhân viên kinh doanh HCSN", // 5 Vị trí tuyển dụng
    JobPositionName: "Nhân viên kinh doanh HCSN", // 7 Tin tuyển dụng
    RecruitmentRoundName: "Offer", // 8 Vòng tuyển dụng
    Score: 0, // 9 Đánh giá
    ChannelName: "Careerbuilder", // 10 Nguồn ứng viên
    ApplyDate: "29/10/2025", // 10.5 Ngày ứng tuyển
    EducationDegreeName: "Đại học", // 11 Trình độ đào tạo
    EducationPlaceName: "Học Viện Tài Chính", // 12 Nơi đào tạo
    EducationMajorName: "Nghệ thuật đa phương tiện", // 13 Chuyên ngành
    WorkPlaceRecent: null, // 14 Nơi làm việc gần đây
    AttractivePersonnel: "Dương Thị Thảo", // 15 Nhân sự khai thác
    PresenterOUName: null, // 16 Đơn vị sử dụng
    //  17 Phù hợp với .. null
    AreaName: "Tây Hồ", //  18 Khu vực
    // 19 Người giới thiệu null
    // 20 THông tin tiếp nhận
    // 21 Thuộc kho tiềm năng
    // 22 Thẻ
    Active: 1, // 23 trạng thái
    Gender: 0, // 24 Giới tính
    DateBirth: "27/08/1997", // 25 Ngày sinh
    Address: "Ninh Bình", //   26 Địa chỉ
    // 27 Lý do loại
    CollaboratorName: null, // 28 Cộng tác viên
    DateApply: "27/10/2025", // 29 Ngày tiếp nhận
    OfferStatus: 1, //  30 Trạng thái mời làm việc
  },

   {
    CandidateID: 594738,
    CandidateName: "Nguyễn Văn A",
    Mobile: "0901234001",
    Email: "nguyenvana@gmail.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Lập trình viên",
    JobPositionName: "Lập trình viên",
    RecruitmentRoundName: "Phỏng vấn 1",
    Score: 0,
    ChannelName: "LinkedIn",
    ApplyDate: "28/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Bách Khoa Hà Nội",
    EducationMajorName: "Công nghệ thông tin",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Trần Thị Bích",
    PresenterOUName: null,
    AreaName: "Cầu Giấy",
    Active: 1,
    Gender: 0,
    DateBirth: "01/01/1995",
    Address: "Hà Nội",
    CollaboratorName: null,
    DateApply: "28/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594739,
    CandidateName: "Lê Thị C",
    Mobile: "0912345678",
    Email: "lethic@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên marketing",
    JobPositionName: "Nhân viên marketing",
    RecruitmentRoundName: "Phỏng vấn 2",
    Score: 0,
    ChannelName: "VietnamWorks",
    ApplyDate: "27/10/2025",
    EducationDegreeName: "Cao đẳng",
    EducationPlaceName: "ĐH Kinh tế Quốc dân",
    EducationMajorName: "Marketing",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Nguyễn Văn D",
    PresenterOUName: null,
    AreaName: "Hồ Chí Minh",
    Active: 1,
    Gender: 1,
    DateBirth: "12/03/1996",
    Address: "Hồ Chí Minh",
    CollaboratorName: null,
    DateApply: "27/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594740,
    CandidateName: "Phạm Văn D",
    Mobile: "0987654321",
    Email: "phamvand@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên chăm sóc khách hàng",
    JobPositionName: "CSKH",
    RecruitmentRoundName: "Offer",
    Score: 0,
    ChannelName: "CareerBuilder",
    ApplyDate: "26/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Ngoại thương",
    EducationMajorName: "Quản trị kinh doanh",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Trần Thị Bích",
    PresenterOUName: null,
    AreaName: "Đà Nẵng",
    Active: 1,
    Gender: 0,
    DateBirth: "15/05/1994",
    Address: "Đà Nẵng",
    CollaboratorName: null,
    DateApply: "26/10/2025",
    OfferStatus: 1,
  },
  {
    CandidateID: 594741,
    CandidateName: "Hoàng Thị E",
    Mobile: "0933445566",
    Email: "hoangthe@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên kinh doanh",
    JobPositionName: "Kinh doanh",
    RecruitmentRoundName: "Phỏng vấn 1",
    Score: 0,
    ChannelName: "LinkedIn",
    ApplyDate: "25/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Bách Khoa TP.HCM",
    EducationMajorName: "Quản trị kinh doanh",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Dương Thị Thảo",
    PresenterOUName: null,
    AreaName: "Hải Phòng",
    Active: 1,
    Gender: 1,
    DateBirth: "20/07/1993",
    Address: "Hải Phòng",
    CollaboratorName: null,
    DateApply: "25/10/2025",
    OfferStatus: 0,
  },
  // --- 16 user còn lại ---
  {
    CandidateID: 594742,
    CandidateName: "Trần Văn F",
    Mobile: null,
    Email: "tranvanf@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên IT",
    JobPositionName: "IT Support",
    RecruitmentRoundName: "Phỏng vấn 2",
    Score: 0,
    ChannelName: "VietnamWorks",
    ApplyDate: "24/10/2025",
    EducationDegreeName: "Cao đẳng",
    EducationPlaceName: null,
    EducationMajorName: "CNTT",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Nguyễn Văn A",
    PresenterOUName: null,
    AreaName: "Hà Nội",
    Active: 1,
    Gender: 0,
    DateBirth: "10/10/1992",
    Address: "Hà Nội",
    CollaboratorName: null,
    DateApply: "24/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594743,
    CandidateName: "Nguyễn Thị G",
    Mobile: null,
    Email: null,
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên kế toán",
    JobPositionName: "Kế toán",
    RecruitmentRoundName: "Offer",
    Score: 0,
    ChannelName: null,
    ApplyDate: "23/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: null,
    EducationMajorName: null,
    WorkPlaceRecent: null,
    AttractivePersonnel: "Hoàng Thị E",
    PresenterOUName: null,
    AreaName: "Hà Nội",
    Active: 1,
    Gender: 1,
    DateBirth: "01/02/1990",
    Address: "Hà Nội",
    CollaboratorName: null,
    DateApply: "23/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594744,
    CandidateName: "Lê Văn H",
    Mobile: "0901122334",
    Email: "levanh@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên kinh doanh",
    JobPositionName: "Kinh doanh",
    RecruitmentRoundName: "Phỏng vấn 1",
    Score: 0,
    ChannelName: "Careerbuilder",
    ApplyDate: "22/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Kinh tế TP.HCM",
    EducationMajorName: "Marketing",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Dương Thị Thảo",
    PresenterOUName: null,
    AreaName: "TP.HCM",
    Active: 1,
    Gender: 0,
    DateBirth: "12/06/1995",
    Address: "TP.HCM",
    CollaboratorName: null,
    DateApply: "22/10/2025",
    OfferStatus: 1,
  },
  {
    CandidateID: 594745,
    CandidateName: "Phan Thị I",
    Mobile: "0911223344",
    Email: "phanthi@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên IT",
    JobPositionName: "IT Developer",
    RecruitmentRoundName: "Offer",
    Score: 0,
    ChannelName: "LinkedIn",
    ApplyDate: "21/10/2025",
    EducationDegreeName: "Cao đẳng",
    EducationPlaceName: null,
    EducationMajorName: "CNTT",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Nguyễn Văn A",
    PresenterOUName: null,
    AreaName: "Hà Nội",
    Active: 1,
    Gender: 1,
    DateBirth: "10/01/1993",
    Address: "Hà Nội",
    CollaboratorName: null,
    DateApply: "21/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594746,
    CandidateName: "Trần Văn J",
    Mobile: "0933445566",
    Email: "tranvanj@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên marketing",
    JobPositionName: "Marketing",
    RecruitmentRoundName: "Phỏng vấn 2",
    Score: 0,
    ChannelName: "VietnamWorks",
    ApplyDate: "20/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Kinh tế Quốc dân",
    EducationMajorName: "Marketing",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Trần Thị Bích",
    PresenterOUName: null,
    AreaName: "Đà Nẵng",
    Active: 1,
    Gender: 0,
    DateBirth: "05/05/1994",
    Address: "Đà Nẵng",
    CollaboratorName: null,
    DateApply: "20/10/2025",
    OfferStatus: 1,
  },
  {
    CandidateID: 594747,
    CandidateName: "Nguyễn Văn K",
    Mobile: "0901111222",
    Email: "nguyenvank@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Lập trình viên",
    JobPositionName: "Lập trình viên",
    RecruitmentRoundName: "Phỏng vấn 1",
    Score: 0,
    ChannelName: "LinkedIn",
    ApplyDate: "19/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Bách Khoa Hà Nội",
    EducationMajorName: "Công nghệ thông tin",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Trần Thị Bích",
    PresenterOUName: null,
    AreaName: "Cầu Giấy",
    Active: 1,
    Gender: 0,
    DateBirth: "02/02/1995",
    Address: "Hà Nội",
    CollaboratorName: null,
    DateApply: "19/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594748,
    CandidateName: "Lê Thị L",
    Mobile: "0911333444",
    Email: "lethil@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên marketing",
    JobPositionName: "Nhân viên marketing",
    RecruitmentRoundName: "Phỏng vấn 2",
    Score: 0,
    ChannelName: "VietnamWorks",
    ApplyDate: "18/10/2025",
    EducationDegreeName: "Cao đẳng",
    EducationPlaceName: "ĐH Kinh tế Quốc dân",
    EducationMajorName: "Marketing",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Nguyễn Văn D",
    PresenterOUName: null,
    AreaName: "Hồ Chí Minh",
    Active: 1,
    Gender: 1,
    DateBirth: "03/03/1996",
    Address: "Hồ Chí Minh",
    CollaboratorName: null,
    DateApply: "18/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594749,
    CandidateName: "Phạm Văn M",
    Mobile: "0988111222",
    Email: "phamvanm@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên chăm sóc khách hàng",
    JobPositionName: "CSKH",
    RecruitmentRoundName: "Offer",
    Score: 0,
    ChannelName: "CareerBuilder",
    ApplyDate: "17/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Ngoại thương",
    EducationMajorName: "Quản trị kinh doanh",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Trần Thị Bích",
    PresenterOUName: null,
    AreaName: "Đà Nẵng",
    Active: 1,
    Gender: 0,
    DateBirth: "04/04/1994",
    Address: "Đà Nẵng",
    CollaboratorName: null,
    DateApply: "17/10/2025",
    OfferStatus: 1,
  },
  {
    CandidateID: 594750,
    CandidateName: "Hoàng Thị N",
    Mobile: "0933556677",
    Email: "hoangthin@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên kinh doanh",
    JobPositionName: "Kinh doanh",
    RecruitmentRoundName: "Phỏng vấn 1",
    Score: 0,
    ChannelName: "LinkedIn",
    ApplyDate: "16/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Bách Khoa TP.HCM",
    EducationMajorName: "Quản trị kinh doanh",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Dương Thị Thảo",
    PresenterOUName: null,
    AreaName: "Hải Phòng",
    Active: 1,
    Gender: 1,
    DateBirth: "05/05/1993",
    Address: "Hải Phòng",
    CollaboratorName: null,
    DateApply: "16/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594747,
    CandidateName: "Nguyễn Văn K",
    Mobile: "0901111222",
    Email: "nguyenvank@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Lập trình viên",
    JobPositionName: "Lập trình viên",
    RecruitmentRoundName: "Phỏng vấn 1",
    Score: 0,
    ChannelName: "LinkedIn",
    ApplyDate: "19/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Bách Khoa Hà Nội",
    EducationMajorName: "Công nghệ thông tin",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Trần Thị Bích",
    PresenterOUName: null,
    AreaName: "Cầu Giấy",
    Active: 1,
    Gender: 0,
    DateBirth: "02/02/1995",
    Address: "Hà Nội",
    CollaboratorName: null,
    DateApply: "19/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594748,
    CandidateName: "Lê Thị L",
    Mobile: "0911333444",
    Email: "lethil@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên marketing",
    JobPositionName: "Nhân viên marketing",
    RecruitmentRoundName: "Phỏng vấn 2",
    Score: 0,
    ChannelName: "VietnamWorks",
    ApplyDate: "18/10/2025",
    EducationDegreeName: "Cao đẳng",
    EducationPlaceName: "ĐH Kinh tế Quốc dân",
    EducationMajorName: "Marketing",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Nguyễn Văn D",
    PresenterOUName: null,
    AreaName: "Hồ Chí Minh",
    Active: 1,
    Gender: 1,
    DateBirth: "03/03/1996",
    Address: "Hồ Chí Minh",
    CollaboratorName: null,
    DateApply: "18/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594749,
    CandidateName: "Phạm Văn M",
    Mobile: "0988111222",
    Email: "phamvanm@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên chăm sóc khách hàng",
    JobPositionName: "CSKH",
    RecruitmentRoundName: "Offer",
    Score: 0,
    ChannelName: "CareerBuilder",
    ApplyDate: "17/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Ngoại thương",
    EducationMajorName: "Quản trị kinh doanh",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Trần Thị Bích",
    PresenterOUName: null,
    AreaName: "Đà Nẵng",
    Active: 1,
    Gender: 0,
    DateBirth: "04/04/1994",
    Address: "Đà Nẵng",
    CollaboratorName: null,
    DateApply: "17/10/2025",
    OfferStatus: 1,
  },
  {
    CandidateID: 594750,
    CandidateName: "Hoàng Thị N",
    Mobile: "0933556677",
    Email: "hoangthin@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên kinh doanh",
    JobPositionName: "Kinh doanh",
    RecruitmentRoundName: "Phỏng vấn 1",
    Score: 0,
    ChannelName: "LinkedIn",
    ApplyDate: "16/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Bách Khoa TP.HCM",
    EducationMajorName: "Quản trị kinh doanh",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Dương Thị Thảo",
    PresenterOUName: null,
    AreaName: "Hải Phòng",
    Active: 1,
    Gender: 1,
    DateBirth: "05/05/1993",
    Address: "Hải Phòng",
    CollaboratorName: null,
    DateApply: "16/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594747,
    CandidateName: "Nguyễn Văn K",
    Mobile: "0901111222",
    Email: "nguyenvank@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Lập trình viên",
    JobPositionName: "Lập trình viên",
    RecruitmentRoundName: "Phỏng vấn 1",
    Score: 0,
    ChannelName: "LinkedIn",
    ApplyDate: "19/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Bách Khoa Hà Nội",
    EducationMajorName: "Công nghệ thông tin",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Trần Thị Bích",
    PresenterOUName: null,
    AreaName: "Cầu Giấy",
    Active: 1,
    Gender: 0,
    DateBirth: "02/02/1995",
    Address: "Hà Nội",
    CollaboratorName: null,
    DateApply: "19/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594748,
    CandidateName: "Lê Thị L",
    Mobile: "0911333444",
    Email: "lethil@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên marketing",
    JobPositionName: "Nhân viên marketing",
    RecruitmentRoundName: "Phỏng vấn 2",
    Score: 0,
    ChannelName: "VietnamWorks",
    ApplyDate: "18/10/2025",
    EducationDegreeName: "Cao đẳng",
    EducationPlaceName: "ĐH Kinh tế Quốc dân",
    EducationMajorName: "Marketing",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Nguyễn Văn D",
    PresenterOUName: null,
    AreaName: "Hồ Chí Minh",
    Active: 1,
    Gender: 1,
    DateBirth: "03/03/1996",
    Address: "Hồ Chí Minh",
    CollaboratorName: null,
    DateApply: "18/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594749,
    CandidateName: "Phạm Văn M",
    Mobile: "0988111222",
    Email: "phamvanm@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên chăm sóc khách hàng",
    JobPositionName: "CSKH",
    RecruitmentRoundName: "Offer",
    Score: 0,
    ChannelName: "CareerBuilder",
    ApplyDate: "17/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Ngoại thương",
    EducationMajorName: "Quản trị kinh doanh",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Trần Thị Bích",
    PresenterOUName: null,
    AreaName: "Đà Nẵng",
    Active: 1,
    Gender: 0,
    DateBirth: "04/04/1994",
    Address: "Đà Nẵng",
    CollaboratorName: null,
    DateApply: "17/10/2025",
    OfferStatus: 1,
  },
  {
    CandidateID: 594750,
    CandidateName: "Hoàng Thị N",
    Mobile: "0933556677",
    Email: "hoangthin@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên kinh doanh",
    JobPositionName: "Kinh doanh",
    RecruitmentRoundName: "Phỏng vấn 1",
    Score: 0,
    ChannelName: "LinkedIn",
    ApplyDate: "16/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Bách Khoa TP.HCM",
    EducationMajorName: "Quản trị kinh doanh",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Dương Thị Thảo",
    PresenterOUName: null,
    AreaName: "Hải Phòng",
    Active: 1,
    Gender: 1,
    DateBirth: "05/05/1993",
    Address: "Hải Phòng",
    CollaboratorName: null,
    DateApply: "16/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594747,
    CandidateName: "Nguyễn Văn K",
    Mobile: "0901111222",
    Email: "nguyenvank@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Lập trình viên",
    JobPositionName: "Lập trình viên",
    RecruitmentRoundName: "Phỏng vấn 1",
    Score: 0,
    ChannelName: "LinkedIn",
    ApplyDate: "19/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Bách Khoa Hà Nội",
    EducationMajorName: "Công nghệ thông tin",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Trần Thị Bích",
    PresenterOUName: null,
    AreaName: "Cầu Giấy",
    Active: 1,
    Gender: 0,
    DateBirth: "02/02/1995",
    Address: "Hà Nội",
    CollaboratorName: null,
    DateApply: "19/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594748,
    CandidateName: "Lê Thị L",
    Mobile: "0911333444",
    Email: "lethil@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên marketing",
    JobPositionName: "Nhân viên marketing",
    RecruitmentRoundName: "Phỏng vấn 2",
    Score: 0,
    ChannelName: "VietnamWorks",
    ApplyDate: "18/10/2025",
    EducationDegreeName: "Cao đẳng",
    EducationPlaceName: "ĐH Kinh tế Quốc dân",
    EducationMajorName: "Marketing",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Nguyễn Văn D",
    PresenterOUName: null,
    AreaName: "Hồ Chí Minh",
    Active: 1,
    Gender: 1,
    DateBirth: "03/03/1996",
    Address: "Hồ Chí Minh",
    CollaboratorName: null,
    DateApply: "18/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594749,
    CandidateName: "Phạm Văn M",
    Mobile: "0988111222",
    Email: "phamvanm@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên chăm sóc khách hàng",
    JobPositionName: "CSKH",
    RecruitmentRoundName: "Offer",
    Score: 0,
    ChannelName: "CareerBuilder",
    ApplyDate: "17/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Ngoại thương",
    EducationMajorName: "Quản trị kinh doanh",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Trần Thị Bích",
    PresenterOUName: null,
    AreaName: "Đà Nẵng",
    Active: 1,
    Gender: 0,
    DateBirth: "04/04/1994",
    Address: "Đà Nẵng",
    CollaboratorName: null,
    DateApply: "17/10/2025",
    OfferStatus: 1,
  },
  {
    CandidateID: 594750,
    CandidateName: "Hoàng Thị N",
    Mobile: "0933556677",
    Email: "hoangthin@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên kinh doanh",
    JobPositionName: "Kinh doanh",
    RecruitmentRoundName: "Phỏng vấn 1",
    Score: 0,
    ChannelName: "LinkedIn",
    ApplyDate: "16/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Bách Khoa TP.HCM",
    EducationMajorName: "Quản trị kinh doanh",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Dương Thị Thảo",
    PresenterOUName: null,
    AreaName: "Hải Phòng",
    Active: 1,
    Gender: 1,
    DateBirth: "05/05/1993",
    Address: "Hải Phòng",
    CollaboratorName: null,
    DateApply: "16/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594747,
    CandidateName: "Nguyễn Văn K",
    Mobile: "0901111222",
    Email: "nguyenvank@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Lập trình viên",
    JobPositionName: "Lập trình viên",
    RecruitmentRoundName: "Phỏng vấn 1",
    Score: 0,
    ChannelName: "LinkedIn",
    ApplyDate: "19/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Bách Khoa Hà Nội",
    EducationMajorName: "Công nghệ thông tin",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Trần Thị Bích",
    PresenterOUName: null,
    AreaName: "Cầu Giấy",
    Active: 1,
    Gender: 0,
    DateBirth: "02/02/1995",
    Address: "Hà Nội",
    CollaboratorName: null,
    DateApply: "19/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594748,
    CandidateName: "Lê Thị L",
    Mobile: "0911333444",
    Email: "lethil@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên marketing",
    JobPositionName: "Nhân viên marketing",
    RecruitmentRoundName: "Phỏng vấn 2",
    Score: 0,
    ChannelName: "VietnamWorks",
    ApplyDate: "18/10/2025",
    EducationDegreeName: "Cao đẳng",
    EducationPlaceName: "ĐH Kinh tế Quốc dân",
    EducationMajorName: "Marketing",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Nguyễn Văn D",
    PresenterOUName: null,
    AreaName: "Hồ Chí Minh",
    Active: 1,
    Gender: 1,
    DateBirth: "03/03/1996",
    Address: "Hồ Chí Minh",
    CollaboratorName: null,
    DateApply: "18/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594749,
    CandidateName: "Phạm Văn M",
    Mobile: "0988111222",
    Email: "phamvanm@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên chăm sóc khách hàng",
    JobPositionName: "CSKH",
    RecruitmentRoundName: "Offer",
    Score: 0,
    ChannelName: "CareerBuilder",
    ApplyDate: "17/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Ngoại thương",
    EducationMajorName: "Quản trị kinh doanh",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Trần Thị Bích",
    PresenterOUName: null,
    AreaName: "Đà Nẵng",
    Active: 1,
    Gender: 0,
    DateBirth: "04/04/1994",
    Address: "Đà Nẵng",
    CollaboratorName: null,
    DateApply: "17/10/2025",
    OfferStatus: 1,
  },
  {
    CandidateID: 594750,
    CandidateName: "Hoàng Thị N",
    Mobile: "0933556677",
    Email: "hoangthin@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên kinh doanh",
    JobPositionName: "Kinh doanh",
    RecruitmentRoundName: "Phỏng vấn 1",
    Score: 0,
    ChannelName: "LinkedIn",
    ApplyDate: "16/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Bách Khoa TP.HCM",
    EducationMajorName: "Quản trị kinh doanh",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Dương Thị Thảo",
    PresenterOUName: null,
    AreaName: "Hải Phòng",
    Active: 1,
    Gender: 1,
    DateBirth: "05/05/1993",
    Address: "Hải Phòng",
    CollaboratorName: null,
    DateApply: "16/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594747,
    CandidateName: "Nguyễn Văn K",
    Mobile: "0901111222",
    Email: "nguyenvank@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Lập trình viên",
    JobPositionName: "Lập trình viên",
    RecruitmentRoundName: "Phỏng vấn 1",
    Score: 0,
    ChannelName: "LinkedIn",
    ApplyDate: "19/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Bách Khoa Hà Nội",
    EducationMajorName: "Công nghệ thông tin",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Trần Thị Bích",
    PresenterOUName: null,
    AreaName: "Cầu Giấy",
    Active: 1,
    Gender: 0,
    DateBirth: "02/02/1995",
    Address: "Hà Nội",
    CollaboratorName: null,
    DateApply: "19/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594748,
    CandidateName: "Lê Thị L",
    Mobile: "0911333444",
    Email: "lethil@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên marketing",
    JobPositionName: "Nhân viên marketing",
    RecruitmentRoundName: "Phỏng vấn 2",
    Score: 0,
    ChannelName: "VietnamWorks",
    ApplyDate: "18/10/2025",
    EducationDegreeName: "Cao đẳng",
    EducationPlaceName: "ĐH Kinh tế Quốc dân",
    EducationMajorName: "Marketing",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Nguyễn Văn D",
    PresenterOUName: null,
    AreaName: "Hồ Chí Minh",
    Active: 1,
    Gender: 1,
    DateBirth: "03/03/1996",
    Address: "Hồ Chí Minh",
    CollaboratorName: null,
    DateApply: "18/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594749,
    CandidateName: "Phạm Văn M",
    Mobile: "0988111222",
    Email: "phamvanm@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên chăm sóc khách hàng",
    JobPositionName: "CSKH",
    RecruitmentRoundName: "Offer",
    Score: 0,
    ChannelName: "CareerBuilder",
    ApplyDate: "17/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Ngoại thương",
    EducationMajorName: "Quản trị kinh doanh",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Trần Thị Bích",
    PresenterOUName: null,
    AreaName: "Đà Nẵng",
    Active: 1,
    Gender: 0,
    DateBirth: "04/04/1994",
    Address: "Đà Nẵng",
    CollaboratorName: null,
    DateApply: "17/10/2025",
    OfferStatus: 1,
  },
  {
    CandidateID: 594750,
    CandidateName: "Hoàng Thị N",
    Mobile: "0933556677",
    Email: "hoangthin@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên kinh doanh",
    JobPositionName: "Kinh doanh",
    RecruitmentRoundName: "Phỏng vấn 1",
    Score: 0,
    ChannelName: "LinkedIn",
    ApplyDate: "16/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Bách Khoa TP.HCM",
    EducationMajorName: "Quản trị kinh doanh",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Dương Thị Thảo",
    PresenterOUName: null,
    AreaName: "Hải Phòng",
    Active: 1,
    Gender: 1,
    DateBirth: "05/05/1993",
    Address: "Hải Phòng",
    CollaboratorName: null,
    DateApply: "16/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594747,
    CandidateName: "Nguyễn Văn K",
    Mobile: "0901111222",
    Email: "nguyenvank@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Lập trình viên",
    JobPositionName: "Lập trình viên",
    RecruitmentRoundName: "Phỏng vấn 1",
    Score: 0,
    ChannelName: "LinkedIn",
    ApplyDate: "19/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Bách Khoa Hà Nội",
    EducationMajorName: "Công nghệ thông tin",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Trần Thị Bích",
    PresenterOUName: null,
    AreaName: "Cầu Giấy",
    Active: 1,
    Gender: 0,
    DateBirth: "02/02/1995",
    Address: "Hà Nội",
    CollaboratorName: null,
    DateApply: "19/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594748,
    CandidateName: "Lê Thị L",
    Mobile: "0911333444",
    Email: "lethil@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên marketing",
    JobPositionName: "Nhân viên marketing",
    RecruitmentRoundName: "Phỏng vấn 2",
    Score: 0,
    ChannelName: "VietnamWorks",
    ApplyDate: "18/10/2025",
    EducationDegreeName: "Cao đẳng",
    EducationPlaceName: "ĐH Kinh tế Quốc dân",
    EducationMajorName: "Marketing",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Nguyễn Văn D",
    PresenterOUName: null,
    AreaName: "Hồ Chí Minh",
    Active: 1,
    Gender: 1,
    DateBirth: "03/03/1996",
    Address: "Hồ Chí Minh",
    CollaboratorName: null,
    DateApply: "18/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594749,
    CandidateName: "Phạm Văn M",
    Mobile: "0988111222",
    Email: "phamvanm@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên chăm sóc khách hàng",
    JobPositionName: "CSKH",
    RecruitmentRoundName: "Offer",
    Score: 0,
    ChannelName: "CareerBuilder",
    ApplyDate: "17/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Ngoại thương",
    EducationMajorName: "Quản trị kinh doanh",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Trần Thị Bích",
    PresenterOUName: null,
    AreaName: "Đà Nẵng",
    Active: 1,
    Gender: 0,
    DateBirth: "04/04/1994",
    Address: "Đà Nẵng",
    CollaboratorName: null,
    DateApply: "17/10/2025",
    OfferStatus: 1,
  },
  {
    CandidateID: 594750,
    CandidateName: "Hoàng Thị N",
    Mobile: "0933556677",
    Email: "hoangthin@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên kinh doanh",
    JobPositionName: "Kinh doanh",
    RecruitmentRoundName: "Phỏng vấn 1",
    Score: 0,
    ChannelName: "LinkedIn",
    ApplyDate: "16/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Bách Khoa TP.HCM",
    EducationMajorName: "Quản trị kinh doanh",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Dương Thị Thảo",
    PresenterOUName: null,
    AreaName: "Hải Phòng",
    Active: 1,
    Gender: 1,
    DateBirth: "05/05/1993",
    Address: "Hải Phòng",
    CollaboratorName: null,
    DateApply: "16/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594747,
    CandidateName: "Nguyễn Văn K",
    Mobile: "0901111222",
    Email: "nguyenvank@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Lập trình viên",
    JobPositionName: "Lập trình viên",
    RecruitmentRoundName: "Phỏng vấn 1",
    Score: 0,
    ChannelName: "LinkedIn",
    ApplyDate: "19/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Bách Khoa Hà Nội",
    EducationMajorName: "Công nghệ thông tin",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Trần Thị Bích",
    PresenterOUName: null,
    AreaName: "Cầu Giấy",
    Active: 1,
    Gender: 0,
    DateBirth: "02/02/1995",
    Address: "Hà Nội",
    CollaboratorName: null,
    DateApply: "19/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594748,
    CandidateName: "Lê Thị L",
    Mobile: "0911333444",
    Email: "lethil@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên marketing",
    JobPositionName: "Nhân viên marketing",
    RecruitmentRoundName: "Phỏng vấn 2",
    Score: 0,
    ChannelName: "VietnamWorks",
    ApplyDate: "18/10/2025",
    EducationDegreeName: "Cao đẳng",
    EducationPlaceName: "ĐH Kinh tế Quốc dân",
    EducationMajorName: "Marketing",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Nguyễn Văn D",
    PresenterOUName: null,
    AreaName: "Hồ Chí Minh",
    Active: 1,
    Gender: 1,
    DateBirth: "03/03/1996",
    Address: "Hồ Chí Minh",
    CollaboratorName: null,
    DateApply: "18/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594749,
    CandidateName: "Phạm Văn M",
    Mobile: "0988111222",
    Email: "phamvanm@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên chăm sóc khách hàng",
    JobPositionName: "CSKH",
    RecruitmentRoundName: "Offer",
    Score: 0,
    ChannelName: "CareerBuilder",
    ApplyDate: "17/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Ngoại thương",
    EducationMajorName: "Quản trị kinh doanh",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Trần Thị Bích",
    PresenterOUName: null,
    AreaName: "Đà Nẵng",
    Active: 1,
    Gender: 0,
    DateBirth: "04/04/1994",
    Address: "Đà Nẵng",
    CollaboratorName: null,
    DateApply: "17/10/2025",
    OfferStatus: 1,
  },
  {
    CandidateID: 594750,
    CandidateName: "Hoàng Thị N",
    Mobile: "0933556677",
    Email: "hoangthin@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên kinh doanh",
    JobPositionName: "Kinh doanh",
    RecruitmentRoundName: "Phỏng vấn 1",
    Score: 0,
    ChannelName: "LinkedIn",
    ApplyDate: "16/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Bách Khoa TP.HCM",
    EducationMajorName: "Quản trị kinh doanh",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Dương Thị Thảo",
    PresenterOUName: null,
    AreaName: "Hải Phòng",
    Active: 1,
    Gender: 1,
    DateBirth: "05/05/1993",
    Address: "Hải Phòng",
    CollaboratorName: null,
    DateApply: "16/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594747,
    CandidateName: "Nguyễn Văn K",
    Mobile: "0901111222",
    Email: "nguyenvank@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Lập trình viên",
    JobPositionName: "Lập trình viên",
    RecruitmentRoundName: "Phỏng vấn 1",
    Score: 0,
    ChannelName: "LinkedIn",
    ApplyDate: "19/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Bách Khoa Hà Nội",
    EducationMajorName: "Công nghệ thông tin",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Trần Thị Bích",
    PresenterOUName: null,
    AreaName: "Cầu Giấy",
    Active: 1,
    Gender: 0,
    DateBirth: "02/02/1995",
    Address: "Hà Nội",
    CollaboratorName: null,
    DateApply: "19/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594748,
    CandidateName: "Lê Thị L",
    Mobile: "0911333444",
    Email: "lethil@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên marketing",
    JobPositionName: "Nhân viên marketing",
    RecruitmentRoundName: "Phỏng vấn 2",
    Score: 0,
    ChannelName: "VietnamWorks",
    ApplyDate: "18/10/2025",
    EducationDegreeName: "Cao đẳng",
    EducationPlaceName: "ĐH Kinh tế Quốc dân",
    EducationMajorName: "Marketing",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Nguyễn Văn D",
    PresenterOUName: null,
    AreaName: "Hồ Chí Minh",
    Active: 1,
    Gender: 1,
    DateBirth: "03/03/1996",
    Address: "Hồ Chí Minh",
    CollaboratorName: null,
    DateApply: "18/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594749,
    CandidateName: "Phạm Văn M",
    Mobile: "0988111222",
    Email: "phamvanm@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên chăm sóc khách hàng",
    JobPositionName: "CSKH",
    RecruitmentRoundName: "Offer",
    Score: 0,
    ChannelName: "CareerBuilder",
    ApplyDate: "17/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Ngoại thương",
    EducationMajorName: "Quản trị kinh doanh",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Trần Thị Bích",
    PresenterOUName: null,
    AreaName: "Đà Nẵng",
    Active: 1,
    Gender: 0,
    DateBirth: "04/04/1994",
    Address: "Đà Nẵng",
    CollaboratorName: null,
    DateApply: "17/10/2025",
    OfferStatus: 1,
  },
  {
    CandidateID: 594750,
    CandidateName: "Hoàng Thị N",
    Mobile: "0933556677",
    Email: "hoangthin@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên kinh doanh",
    JobPositionName: "Kinh doanh",
    RecruitmentRoundName: "Phỏng vấn 1",
    Score: 0,
    ChannelName: "LinkedIn",
    ApplyDate: "16/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Bách Khoa TP.HCM",
    EducationMajorName: "Quản trị kinh doanh",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Dương Thị Thảo",
    PresenterOUName: null,
    AreaName: "Hải Phòng",
    Active: 1,
    Gender: 1,
    DateBirth: "05/05/1993",
    Address: "Hải Phòng",
    CollaboratorName: null,
    DateApply: "16/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594747,
    CandidateName: "Nguyễn Văn K",
    Mobile: "0901111222",
    Email: "nguyenvank@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Lập trình viên",
    JobPositionName: "Lập trình viên",
    RecruitmentRoundName: "Phỏng vấn 1",
    Score: 0,
    ChannelName: "LinkedIn",
    ApplyDate: "19/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Bách Khoa Hà Nội",
    EducationMajorName: "Công nghệ thông tin",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Trần Thị Bích",
    PresenterOUName: null,
    AreaName: "Cầu Giấy",
    Active: 1,
    Gender: 0,
    DateBirth: "02/02/1995",
    Address: "Hà Nội",
    CollaboratorName: null,
    DateApply: "19/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594748,
    CandidateName: "Lê Thị L",
    Mobile: "0911333444",
    Email: "lethil@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên marketing",
    JobPositionName: "Nhân viên marketing",
    RecruitmentRoundName: "Phỏng vấn 2",
    Score: 0,
    ChannelName: "VietnamWorks",
    ApplyDate: "18/10/2025",
    EducationDegreeName: "Cao đẳng",
    EducationPlaceName: "ĐH Kinh tế Quốc dân",
    EducationMajorName: "Marketing",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Nguyễn Văn D",
    PresenterOUName: null,
    AreaName: "Hồ Chí Minh",
    Active: 1,
    Gender: 1,
    DateBirth: "03/03/1996",
    Address: "Hồ Chí Minh",
    CollaboratorName: null,
    DateApply: "18/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594749,
    CandidateName: "Phạm Văn M",
    Mobile: "0988111222",
    Email: "phamvanm@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên chăm sóc khách hàng",
    JobPositionName: "CSKH",
    RecruitmentRoundName: "Offer",
    Score: 0,
    ChannelName: "CareerBuilder",
    ApplyDate: "17/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Ngoại thương",
    EducationMajorName: "Quản trị kinh doanh",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Trần Thị Bích",
    PresenterOUName: null,
    AreaName: "Đà Nẵng",
    Active: 1,
    Gender: 0,
    DateBirth: "04/04/1994",
    Address: "Đà Nẵng",
    CollaboratorName: null,
    DateApply: "17/10/2025",
    OfferStatus: 1,
  },
  {
    CandidateID: 594750,
    CandidateName: "Hoàng Thị N",
    Mobile: "0933556677",
    Email: "hoangthin@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên kinh doanh",
    JobPositionName: "Kinh doanh",
    RecruitmentRoundName: "Phỏng vấn 1",
    Score: 0,
    ChannelName: "LinkedIn",
    ApplyDate: "16/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Bách Khoa TP.HCM",
    EducationMajorName: "Quản trị kinh doanh",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Dương Thị Thảo",
    PresenterOUName: null,
    AreaName: "Hải Phòng",
    Active: 1,
    Gender: 1,
    DateBirth: "05/05/1993",
    Address: "Hải Phòng",
    CollaboratorName: null,
    DateApply: "16/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594747,
    CandidateName: "Nguyễn Văn K",
    Mobile: "0901111222",
    Email: "nguyenvank@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Lập trình viên",
    JobPositionName: "Lập trình viên",
    RecruitmentRoundName: "Phỏng vấn 1",
    Score: 0,
    ChannelName: "LinkedIn",
    ApplyDate: "19/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Bách Khoa Hà Nội",
    EducationMajorName: "Công nghệ thông tin",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Trần Thị Bích",
    PresenterOUName: null,
    AreaName: "Cầu Giấy",
    Active: 1,
    Gender: 0,
    DateBirth: "02/02/1995",
    Address: "Hà Nội",
    CollaboratorName: null,
    DateApply: "19/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594748,
    CandidateName: "Lê Thị L",
    Mobile: "0911333444",
    Email: "lethil@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên marketing",
    JobPositionName: "Nhân viên marketing",
    RecruitmentRoundName: "Phỏng vấn 2",
    Score: 0,
    ChannelName: "VietnamWorks",
    ApplyDate: "18/10/2025",
    EducationDegreeName: "Cao đẳng",
    EducationPlaceName: "ĐH Kinh tế Quốc dân",
    EducationMajorName: "Marketing",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Nguyễn Văn D",
    PresenterOUName: null,
    AreaName: "Hồ Chí Minh",
    Active: 1,
    Gender: 1,
    DateBirth: "03/03/1996",
    Address: "Hồ Chí Minh",
    CollaboratorName: null,
    DateApply: "18/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594749,
    CandidateName: "Phạm Văn M",
    Mobile: "0988111222",
    Email: "phamvanm@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên chăm sóc khách hàng",
    JobPositionName: "CSKH",
    RecruitmentRoundName: "Offer",
    Score: 0,
    ChannelName: "CareerBuilder",
    ApplyDate: "17/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Ngoại thương",
    EducationMajorName: "Quản trị kinh doanh",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Trần Thị Bích",
    PresenterOUName: null,
    AreaName: "Đà Nẵng",
    Active: 1,
    Gender: 0,
    DateBirth: "04/04/1994",
    Address: "Đà Nẵng",
    CollaboratorName: null,
    DateApply: "17/10/2025",
    OfferStatus: 1,
  },
  {
    CandidateID: 594750,
    CandidateName: "Hoàng Thị N",
    Mobile: "0933556677",
    Email: "hoangthin@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên kinh doanh",
    JobPositionName: "Kinh doanh",
    RecruitmentRoundName: "Phỏng vấn 1",
    Score: 0,
    ChannelName: "LinkedIn",
    ApplyDate: "16/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Bách Khoa TP.HCM",
    EducationMajorName: "Quản trị kinh doanh",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Dương Thị Thảo",
    PresenterOUName: null,
    AreaName: "Hải Phòng",
    Active: 1,
    Gender: 1,
    DateBirth: "05/05/1993",
    Address: "Hải Phòng",
    CollaboratorName: null,
    DateApply: "16/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594747,
    CandidateName: "Nguyễn Văn K",
    Mobile: "0901111222",
    Email: "nguyenvank@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Lập trình viên",
    JobPositionName: "Lập trình viên",
    RecruitmentRoundName: "Phỏng vấn 1",
    Score: 0,
    ChannelName: "LinkedIn",
    ApplyDate: "19/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Bách Khoa Hà Nội",
    EducationMajorName: "Công nghệ thông tin",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Trần Thị Bích",
    PresenterOUName: null,
    AreaName: "Cầu Giấy",
    Active: 1,
    Gender: 0,
    DateBirth: "02/02/1995",
    Address: "Hà Nội",
    CollaboratorName: null,
    DateApply: "19/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594748,
    CandidateName: "Lê Thị L",
    Mobile: "0911333444",
    Email: "lethil@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên marketing",
    JobPositionName: "Nhân viên marketing",
    RecruitmentRoundName: "Phỏng vấn 2",
    Score: 0,
    ChannelName: "VietnamWorks",
    ApplyDate: "18/10/2025",
    EducationDegreeName: "Cao đẳng",
    EducationPlaceName: "ĐH Kinh tế Quốc dân",
    EducationMajorName: "Marketing",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Nguyễn Văn D",
    PresenterOUName: null,
    AreaName: "Hồ Chí Minh",
    Active: 1,
    Gender: 1,
    DateBirth: "03/03/1996",
    Address: "Hồ Chí Minh",
    CollaboratorName: null,
    DateApply: "18/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594749,
    CandidateName: "Phạm Văn M",
    Mobile: "0988111222",
    Email: "phamvanm@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên chăm sóc khách hàng",
    JobPositionName: "CSKH",
    RecruitmentRoundName: "Offer",
    Score: 0,
    ChannelName: "CareerBuilder",
    ApplyDate: "17/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Ngoại thương",
    EducationMajorName: "Quản trị kinh doanh",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Trần Thị Bích",
    PresenterOUName: null,
    AreaName: "Đà Nẵng",
    Active: 1,
    Gender: 0,
    DateBirth: "04/04/1994",
    Address: "Đà Nẵng",
    CollaboratorName: null,
    DateApply: "17/10/2025",
    OfferStatus: 1,
  },
  {
    CandidateID: 594750,
    CandidateName: "Hoàng Thị N",
    Mobile: "0933556677",
    Email: "hoangthin@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên kinh doanh",
    JobPositionName: "Kinh doanh",
    RecruitmentRoundName: "Phỏng vấn 1",
    Score: 0,
    ChannelName: "LinkedIn",
    ApplyDate: "16/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Bách Khoa TP.HCM",
    EducationMajorName: "Quản trị kinh doanh",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Dương Thị Thảo",
    PresenterOUName: null,
    AreaName: "Hải Phòng",
    Active: 1,
    Gender: 1,
    DateBirth: "05/05/1993",
    Address: "Hải Phòng",
    CollaboratorName: null,
    DateApply: "16/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594747,
    CandidateName: "Nguyễn Văn K",
    Mobile: "0901111222",
    Email: "nguyenvank@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Lập trình viên",
    JobPositionName: "Lập trình viên",
    RecruitmentRoundName: "Phỏng vấn 1",
    Score: 0,
    ChannelName: "LinkedIn",
    ApplyDate: "19/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Bách Khoa Hà Nội",
    EducationMajorName: "Công nghệ thông tin",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Trần Thị Bích",
    PresenterOUName: null,
    AreaName: "Cầu Giấy",
    Active: 1,
    Gender: 0,
    DateBirth: "02/02/1995",
    Address: "Hà Nội",
    CollaboratorName: null,
    DateApply: "19/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594748,
    CandidateName: "Lê Thị L",
    Mobile: "0911333444",
    Email: "lethil@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên marketing",
    JobPositionName: "Nhân viên marketing",
    RecruitmentRoundName: "Phỏng vấn 2",
    Score: 0,
    ChannelName: "VietnamWorks",
    ApplyDate: "18/10/2025",
    EducationDegreeName: "Cao đẳng",
    EducationPlaceName: "ĐH Kinh tế Quốc dân",
    EducationMajorName: "Marketing",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Nguyễn Văn D",
    PresenterOUName: null,
    AreaName: "Hồ Chí Minh",
    Active: 1,
    Gender: 1,
    DateBirth: "03/03/1996",
    Address: "Hồ Chí Minh",
    CollaboratorName: null,
    DateApply: "18/10/2025",
    OfferStatus: 0,
  },
  {
    CandidateID: 594749,
    CandidateName: "Phạm Văn M",
    Mobile: "0988111222",
    Email: "phamvanm@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên chăm sóc khách hàng",
    JobPositionName: "CSKH",
    RecruitmentRoundName: "Offer",
    Score: 0,
    ChannelName: "CareerBuilder",
    ApplyDate: "17/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Ngoại thương",
    EducationMajorName: "Quản trị kinh doanh",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Trần Thị Bích",
    PresenterOUName: null,
    AreaName: "Đà Nẵng",
    Active: 1,
    Gender: 0,
    DateBirth: "04/04/1994",
    Address: "Đà Nẵng",
    CollaboratorName: null,
    DateApply: "17/10/2025",
    OfferStatus: 1,
  },
  {
    CandidateID: 594750,
    CandidateName: "Hoàng Thị N",
    Mobile: "0933556677",
    Email: "hoangthin@example.com",
    RecruitmentCampaignNames: null,
    RecruitmentName: "Nhân viên kinh doanh",
    JobPositionName: "Kinh doanh",
    RecruitmentRoundName: "Phỏng vấn 1",
    Score: 0,
    ChannelName: "LinkedIn",
    ApplyDate: "16/10/2025",
    EducationDegreeName: "Đại học",
    EducationPlaceName: "ĐH Bách Khoa TP.HCM",
    EducationMajorName: "Quản trị kinh doanh",
    WorkPlaceRecent: null,
    AttractivePersonnel: "Dương Thị Thảo",
    PresenterOUName: null,
    AreaName: "Hải Phòng",
    Active: 1,
    Gender: 1,
    DateBirth: "05/05/1993",
    Address: "Hải Phòng",
    CollaboratorName: null,
    DateApply: "16/10/2025",
    OfferStatus: 0,
  },
  
  
];

